# Generated by Django 4.2.1 on 2024-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0002_remove_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_create'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
