# Generated by Django 4.2.1 on 2024-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0003_alter_news_options_news_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parameters', models.TextField(blank=True)),
                ('room', models.CharField(choices=[('default', 'Обычный зал'), ('vip', 'Вип зал'), ('premium', 'Премиум зал')], default='default', max_length=20)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
